// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-d1Lbi1w6rIzjHRu89y8uCutdKTfpoJU',
    appId: '1:696159221650:web:2e0b708667a13ca094f34b',
    messagingSenderId: '696159221650',
    projectId: 'sutapa-notes',
    authDomain: 'sutapa-notes.firebaseapp.com',
    storageBucket: 'sutapa-notes.firebasestorage.app',
    measurementId: 'G-FED3YFBDNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCL4IzUniwG6ex9Ds0-h1VI_Ompw36YgM',
    appId: '1:696159221650:android:606c86bce6858f7c94f34b',
    messagingSenderId: '696159221650',
    projectId: 'sutapa-notes',
    storageBucket: 'sutapa-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTOkf9_Jk2Yy5GBm-ehAlbOqq-uY9qgk',
    appId: '1:696159221650:ios:70d8079bfaef54ee94f34b',
    messagingSenderId: '696159221650',
    projectId: 'sutapa-notes',
    storageBucket: 'sutapa-notes.firebasestorage.app',
    iosBundleId: 'com.example.demoAppLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTOkf9_Jk2Yy5GBm-ehAlbOqq-uY9qgk',
    appId: '1:696159221650:ios:70d8079bfaef54ee94f34b',
    messagingSenderId: '696159221650',
    projectId: 'sutapa-notes',
    storageBucket: 'sutapa-notes.firebasestorage.app',
    iosBundleId: 'com.example.demoAppLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-d1Lbi1w6rIzjHRu89y8uCutdKTfpoJU',
    appId: '1:696159221650:web:a79cf24d2012202094f34b',
    messagingSenderId: '696159221650',
    projectId: 'sutapa-notes',
    authDomain: 'sutapa-notes.firebaseapp.com',
    storageBucket: 'sutapa-notes.firebasestorage.app',
    measurementId: 'G-T5LR2C36NK',
  );
}
